version: '3'

volumes:
  esdata: {}

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    environment:
      bootstrap.memory_lock: "true"
      cluster.name: "docker-cluster"
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    env_file:
      - env.local
    ports:
      - "9200"
      - "9300"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
  elastalert:
    build:
      context: .
    cap_add:
      - SYS_NICE
      - SYS_TIME
    depends_on:
      - elasticsearch
    env_file:
      - env.local
