version: '3.3'

volumes:
  elasticsearchdata:

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - discovery.type=single-node
    env_file:
      - ./env.local
    ports:
      - "9200"
      - "9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
  elastalert:
    build: .
    image: travix/elastalert:latest
    healthcheck:
      test: ["CMD-SHELL", "ps -ef | grep elastalert >/dev/null 2>&1"]
      interval: 10s
      retries: 3
      timeout: 10s
    cap_add:
      - SYS_NICE
      - SYS_TIME
    depends_on:
      - elasticsearch
    env_file:
      - ./env.local
